[package]
name = "gdek"
version = "0.1.0"
edition = "2021"
license = "CC0-1.0"

[dependencies]
clap = { version = "3.2.17", features = ["derive"] }
edit = "0.1.5"
image = "0.24.3"
rand_seeder = "0.2.3"
rand_pcg = "0.3.1"
rand = "0.8.5"
convert_case = "0.6.0"
