pub const HEADER: &str = "# Generated by gnomeorbs: 
# See https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html#example for key descriptions
[Desktop Entry]
Type=Application
";

pub const EMPTY_LINES: &str = "# GenericName=
# NoDisplay=
# Comment=
# Hidden=
# OnlyShowIn=
# NotShownIn=
# DBusActivatable=
# TryExec=
# Path=
# Actions=
# MimeType=
# Categories=
# Implements=
# StartupNotify=
# StartupWMClass=
# URL=
# PrefersNonDefaultGPU=
# SingleMainWindow=
# Version=
";
